### ISSUE TITLE
Dotted underline for abbreviations

### ISSUE THREAD

**Issue by hagenw** [sfstoolbox/sfs-documentation#24]
Abbreviations like WFS getting two dotted lines below their letters in the HTML version. This is due to the following css entries:
```css
abbr[title] {
￼    border-bottom: 1px dotted;
}
```
as added by `sphinx_rtd_theme.css` and
```css
abbr[title], acronym[title] {
    text-decoration: underline dotted;
}
```
added by most of the browsers.

The ideal case would be that RTD is changing its theme. Another alternative would be to overwrite the value in a local theme addition (if this is possible).
